# Rust formatting configuration
# See: https://rust-lang.github.io/rustfmt/

edition = "2024"
max_width = 100
tab_spaces = 4
use_small_heuristics = "Default"

# Imports
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true

# Comments
wrap_comments = false
normalize_comments = false
format_code_in_doc_comments = true

# Other
format_strings = false
format_macro_matchers = true
